package main

// English help descriptions for --help-lang en
var helpEN = map[string]string{
	"h":              "Show help",
	"help":           "Show help",
	"help-lang":      "Help language: zh|en",
	"X":              "Specify HTTP method",
	"H":              "Add request header; repeatable",
	"d":              "Request body data; supports @file or @- for stdin; repeatable",
	"data-urlencode": "URL-encode data (name=value or @file); repeatable",
	"F":              "Multipart form field, e.g., name=value or name=@file;type=...; repeatable",
	"json":           "Send JSON body; sets Content-Type: application/json; supports @file or @-",
	"i":              "Include response headers in output",
	"I":              "HEAD only (fetch headers)",
	"L":              "Follow redirects",
	"k":              "Skip TLS certificate verification",
	"m":              "Max time in seconds (0 = unlimited)",
	"o":              "Write response body to file",
	"u":              "Basic auth user:password",
	"v":              "Verbose debug output",
	// removed in parser; keep mapping if shown from en help generation path
	"status-only":     "(removed) Use --x-sc instead",
	"proxy":           "HTTP proxy, e.g., http://127.0.0.1:8080",
	"x":               "Alias of --proxy",
	"b":               "Send cookies like 'a=1; b=2' or @file",
	"raw":             "Return raw compressed body (disable auto-decompress)",
	"concurrency":     "Concurrency",
	"repeat":          "Repeat request count (total attempts)",
	"expect-string":   "Expect fixed substring in body; exit 22 if missing",
	"trace":           "Print timing analysis (DNS/TCP/TLS/TTFB/Total)",
	"A":               "User-Agent value",
	"json-out":        "Output result as JSON",
	"json-body-plain": "In JSON result, keep body as plain string (not base64)",
	"compressed":      "Ask for compressed response (sets Accept-Encoding: gzip)",
	"connect-timeout": "Connect timeout in seconds",
	"D":               "Write response headers to file (-D)",
	"dump-header":     "Write response headers to file",
	"c":               "Write cookies to file after operation (-c)",
	"cookie-jar":      "Write cookies to file after operation",
	"G":               "Append -d data to URL and use GET",
	"url-query":       "Append URL query string name=value&k=v",
	"r":               "Range request (-r)",
	"range":           "Range request",
	"f":               "Fail on HTTP errors (-f)",
	"fail":            "Fail on HTTP errors",
	"retry":           "Retry count",
	"retry-delay":     "Retry delay in seconds",
	"retry-max-time":  "Max total retry time in seconds",
	"O":               "Save with remote name (-O)",
	"J":               "Use filename from response header (-J)",
	"output-dir":      "Output directory",
	"create-dirs":     "Create local directories if needed",
	"max-redirs":      "Maximum redirects",
	"http1.0":         "Use HTTP/1.0",
	"http1.1":         "Use HTTP/1.1",
	"http2":           "Use HTTP/2",
	"T":               "Upload file (-T)",
	"upload-file":     "Upload file",
	"w":               "Write-out format (-w)",
	"write-out":       "Write-out format",
	"stderr":          "Redirect stderr to file",
	"output-template": "Output file template for multi-run, e.g., out-{index}.bin",
	"duration":        "Load test duration (seconds)",
	"rate":            "Requests per second (RPS)",
	"summary":         "Summary only",
	"summary-json":    "Output summary as JSON",
	"no-body":         "Discard response body during load test",
	"no-jar":          "Disable CookieJar (recommended for load test)",
	"max-body-bytes":  "Max body bytes to keep in JSON output (0 = unlimited)",
	"data-file":       "Use file as x-www-form-urlencoded body (streaming)",
	"json-file":       "Use file as application/json body (streaming)",
	"pretty":          "Pretty summary output",
	"no-pretty":       "Disable pretty summary output",
	// extract shortcuts
	"x-sc":     "Print status code only",
	"x-server": "Print response header Server",
	"x-ct":     "Print response header Content-Type",
	"x-proto":  "Print HTTP protocol",
	"x-url":    "Print effective URL",
	"x-loc":    "Print response header Location",
	"x-header": "Print specified response header(s), repeatable",
	"x-sep":    "Separator for multiple extracts (default newline)",
}
